In [1]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_digits
digits = load_digits()

In [2]:
dir(digits)

['DESCR', 'data', 'feature_names', 'frame', 'images', 'target', 'target_names']

In [5]:
digits.data[:3]

array([[ 0.,  0.,  5., 13.,  9.,  1.,  0.,  0.,  0.,  0., 13., 15., 10.,
        15.,  5.,  0.,  0.,  3., 15.,  2.,  0., 11.,  8.,  0.,  0.,  4.,
        12.,  0.,  0.,  8.,  8.,  0.,  0.,  5.,  8.,  0.,  0.,  9.,  8.,
         0.,  0.,  4., 11.,  0.,  1., 12.,  7.,  0.,  0.,  2., 14.,  5.,
        10., 12.,  0.,  0.,  0.,  0.,  6., 13., 10.,  0.,  0.,  0.],
       [ 0.,  0.,  0., 12., 13.,  5.,  0.,  0.,  0.,  0.,  0., 11., 16.,
         9.,  0.,  0.,  0.,  0.,  3., 15., 16.,  6.,  0.,  0.,  0.,  7.,
        15., 16., 16.,  2.,  0.,  0.,  0.,  0.,  1., 16., 16.,  3.,  0.,
         0.,  0.,  0.,  1., 16., 16.,  6.,  0.,  0.,  0.,  0.,  1., 16.,
        16.,  6.,  0.,  0.,  0.,  0.,  0., 11., 16., 10.,  0.,  0.],
       [ 0.,  0.,  0.,  4., 15., 12.,  0.,  0.,  0.,  0.,  3., 16., 15.,
        14.,  0.,  0.,  0.,  0.,  8., 13.,  8., 16.,  0.,  0.,  0.,  0.,
         1.,  6., 15., 11.,  0.,  0.,  0.,  1.,  8., 13., 15.,  1.,  0.,
         0.,  0.,  9., 16., 16.,  5.,  0.,  0.,  0.,  0.,  

In [4]:
digits.feature_names[:3]

['pixel_0_0', 'pixel_0_1', 'pixel_0_2']

In [14]:
digits.target_names

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
digits.target[:20]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
print(digits.data.shape)
print(digits.target.shape)

(1797, 64)
(1797,)


In [18]:
df = pd.DataFrame(digits.data,digits.target)
df

0    1     2     3     4     5    6    7    8    9   ...   54   55   56  \
0   0.0  0.0   5.0  13.0   9.0   1.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
1   0.0  0.0   0.0  12.0  13.0   5.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
2   0.0  0.0   0.0   4.0  15.0  12.0  0.0  0.0  0.0  0.0  ...  5.0  0.0  0.0   
3   0.0  0.0   7.0  15.0  13.0   1.0  0.0  0.0  0.0  8.0  ...  9.0  0.0  0.0   
4   0.0  0.0   0.0   1.0  11.0   0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
..  ...  ...   ...   ...   ...   ...  ...  ...  ...  ...  ...  ...  ...  ...   
9   0.0  0.0   4.0  10.0  13.0   6.0  0.0  0.0  0.0  1.0  ...  4.0  0.0  0.0   
0   0.0  0.0   6.0  16.0  13.0  11.0  1.0  0.0  0.0  0.0  ...  1.0  0.0  0.0   
8   0.0  0.0   1.0  11.0  15.0   1.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
9   0.0  0.0   2.0  10.0   7.0   0.0  0.0  0.0  0.0  0.0  ...  2.0  0.0  0.0   
8   0.0  0.0  10.0  14.0   8.0   1.0  0.0  0.0  0.0  2.0  ...  8.0  0.0  0.0   

     57   58    59    60    61   62   63  
0   0.0  6.0  13.0  10.0   0.0  0.0  0.0  
1   0.0  0.0  11.0  16.0  10.0  0.0  0.0  
2   0.0  0.0   3.0  11.0  16.0  9.0  0.0  
3   0.0  7.0  13.0  13.0   9.0  0.0  0.0  
4   0.0  0.0   2.0  16.0   4.0  0.0  0.0  
..  ...  ...   ...   ...   ...  ...  ...  
9   0.0  2.0  14.0  15.0   9.0  0.0  0.0  
0   0.0  6.0  16.0  14.0   6.0  0.0  0.0  
8   0.0  2.0   9.0  13.0   6.0  0.0  0.0  
9   0.0  5.0  12.0  16.0  12.0  0.0  0.0  
8   1.0  8.0  12.0  14.0  12.0  1.0  0.0  

[1797 rows x 64 columns]

In [20]:
df['target'] = digits.target
df

0    1     2     3     4     5    6    7    8    9  ...   55   56   57  \
0   0.0  0.0   5.0  13.0   9.0   1.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
1   0.0  0.0   0.0  12.0  13.0   5.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
2   0.0  0.0   0.0   4.0  15.0  12.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
3   0.0  0.0   7.0  15.0  13.0   1.0  0.0  0.0  0.0  8.0  ...  0.0  0.0  0.0   
4   0.0  0.0   0.0   1.0  11.0   0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
..  ...  ...   ...   ...   ...   ...  ...  ...  ...  ...  ...  ...  ...  ...   
9   0.0  0.0   4.0  10.0  13.0   6.0  0.0  0.0  0.0  1.0  ...  0.0  0.0  0.0   
0   0.0  0.0   6.0  16.0  13.0  11.0  1.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
8   0.0  0.0   1.0  11.0  15.0   1.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
9   0.0  0.0   2.0  10.0   7.0   0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
8   0.0  0.0  10.0  14.0   8.0   1.0  0.0  0.0  0.0  2.0  ...  0.0  0.0  1.0   

     58    59    60    61   62   63  target  
0   6.0  13.0  10.0   0.0  0.0  0.0       0  
1   0.0  11.0  16.0  10.0  0.0  0.0       1  
2   0.0   3.0  11.0  16.0  9.0  0.0       2  
3   7.0  13.0  13.0   9.0  0.0  0.0       3  
4   0.0   2.0  16.0   4.0  0.0  0.0       4  
..  ...   ...   ...   ...  ...  ...     ...  
9   2.0  14.0  15.0   9.0  0.0  0.0       9  
0   6.0  16.0  14.0   6.0  0.0  0.0       0  
8   2.0   9.0  13.0   6.0  0.0  0.0       8  
9   5.0  12.0  16.0  12.0  0.0  0.0       9  
8   8.0  12.0  14.0  12.0  1.0  0.0       8  

[1797 rows x 65 columns]

In [23]:
X = df.drop('target', axis='columns')
X

0    1     2     3     4     5    6    7    8    9   ...   54   55   56  \
0   0.0  0.0   5.0  13.0   9.0   1.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
1   0.0  0.0   0.0  12.0  13.0   5.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
2   0.0  0.0   0.0   4.0  15.0  12.0  0.0  0.0  0.0  0.0  ...  5.0  0.0  0.0   
3   0.0  0.0   7.0  15.0  13.0   1.0  0.0  0.0  0.0  8.0  ...  9.0  0.0  0.0   
4   0.0  0.0   0.0   1.0  11.0   0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
..  ...  ...   ...   ...   ...   ...  ...  ...  ...  ...  ...  ...  ...  ...   
9   0.0  0.0   4.0  10.0  13.0   6.0  0.0  0.0  0.0  1.0  ...  4.0  0.0  0.0   
0   0.0  0.0   6.0  16.0  13.0  11.0  1.0  0.0  0.0  0.0  ...  1.0  0.0  0.0   
8   0.0  0.0   1.0  11.0  15.0   1.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
9   0.0  0.0   2.0  10.0   7.0   0.0  0.0  0.0  0.0  0.0  ...  2.0  0.0  0.0   
8   0.0  0.0  10.0  14.0   8.0   1.0  0.0  0.0  0.0  2.0  ...  8.0  0.0  0.0   

     57   58    59    60    61   62   63  
0   0.0  6.0  13.0  10.0   0.0  0.0  0.0  
1   0.0  0.0  11.0  16.0  10.0  0.0  0.0  
2   0.0  0.0   3.0  11.0  16.0  9.0  0.0  
3   0.0  7.0  13.0  13.0   9.0  0.0  0.0  
4   0.0  0.0   2.0  16.0   4.0  0.0  0.0  
..  ...  ...   ...   ...   ...  ...  ...  
9   0.0  2.0  14.0  15.0   9.0  0.0  0.0  
0   0.0  6.0  16.0  14.0   6.0  0.0  0.0  
8   0.0  2.0   9.0  13.0   6.0  0.0  0.0  
9   0.0  5.0  12.0  16.0  12.0  0.0  0.0  
8   1.0  8.0  12.0  14.0  12.0  1.0  0.0  

[1797 rows x 64 columns]

In [25]:
y = df.target
y

0    0
1    1
2    2
3    3
4    4
    ..
9    9
0    0
8    8
9    9
8    8
Name: target, Length: 1797, dtype: int64

In [27]:
from sklearn.model_selection import train_test_split 
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2)

In [30]:
from sklearn.svm import SVC
# with RBF kernel 
model_rbf = SVC()
model_rbf.fit(X_train, y_train)

SVC()

In [31]:
model_rbf.score(X_test, y_test)

0.9916666666666667

In [34]:
# with linear kernel 
model_linear = SVC(kernel='linear')
model_linear.fit(X_train, y_train)
model_linear.score(X_test, y_test)

0.9777777777777777

In [41]:
# with C>1, no changes; C<1, reduced performance
model_c = SVC(C=0.2)
model_c.fit(X_train, y_train)
model_c.score(X_test, y_test)

0.9777777777777777

In [40]:
# with gamma = auto 
model_g = SVC(gamma='auto')
model_g.fit(X_train, y_train)
model_g.score(X_test, y_test)

0.5